[supervisord]
nodaemon=true

[program:bot]
command=python /app/bot.py
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:server]
command=gunicorn --bind 0.0.0.0:8000 server:app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
